version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/node:latest
        environment:
            BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    checkout:
      post:
        - bundle install
        - bash automated_build.sh

    steps:
      - checkout

      - run: gem update --system
      - run: gem install bundler
      - run: bundle install
      - run: npm install --save firebase-tools

      - run:
          name: Jekyll contentful
          command: bundle exec jekyll contentful
      - run:
          name: install dependencies
          command: bundle exec jekyll build
      - run:
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
