version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/node:latest
        environment:
            BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    checkout:
      post:
        - bundle install
        - bash automated_build.sh

    steps:
      - checkout

      - run:
          name: Jekyll contentful
          command: bundle exec jekyll contentful
      - run:
          name: install dependencies
          command: bundle exec jekyll build
      - run:
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
      - run:
          name: Installing Deps
          command: gem update --system && gem install bundler && npm install --save firebase-tools && bundle install && bundle exec jekyll contentful && bundle exec jekyll build && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          when: on_fail

