version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/node:latest
        environment:
            BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    dependencies:
      pre:
        - gem update --system
        - gem install bundler
        - npm install --save firebase-tools

    checkout:
      post:
        - bundle install
        - bash automated_build.sh

    steps:
      - checkout

      - run: bundle install

      - run:
          name: Jekyll contentful
          command: bundle exec jekyll contentful
      - run:
          name: install dependencies
          command: bundle exec jekyll build
      - run:
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
